name: Java CI/CD with AWS Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: udehnih-auth
          path: build/libs/*.jar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: udehnih-auth
          path: build/libs/

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create deployment package
        run: |
          mkdir -p .ebextensions
          echo "option_settings:" > .ebextensions/env.config
          echo "  aws:elasticbeanstalk:application:environment:" >> .ebextensions/env.config
          echo "    SERVER_PORT: 5000" >> .ebextensions/env.config
          echo "web: java -jar build/libs/udehnih-auth-0.0.1-SNAPSHOT.jar" > Procfile
          zip -r deploy.zip build/libs/udehnih-auth-0.0.1-SNAPSHOT.jar Procfile .ebextensions/

      - name: Deploy to Elastic Beanstalk
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.AWS_S3_BUCKET }}/deploy-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APPLICATION_NAME }} \
            --version-label "ver-${{ github.sha }}" \
            --source-bundle S3Bucket="${{ secrets.AWS_S3_BUCKET }}",S3Key="deploy-${{ github.sha }}.zip"
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }} \
            --version-label "ver-${{ github.sha }}"